FROM python:3.10-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    sox \
    libsndfile1 \
    libsox-fmt-all \
    ffmpeg \
    libhdf5-dev \
  && rm -rf /var/lib/apt/lists/*

COPY . /basic-pitch
WORKDIR /basic-pitch
RUN --mount=type=cache,target=/root/.cache \
  pip3 install --upgrade pip && \
  pip3 install --upgrade setuptools wheel && \
  pip3 install "numpy<2" tflite-runtime && \
  pip3 install basic-pitch
