[project]
name = "vocal-isolater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "moviepy",
    "yt-dlp>=2025.6.30",
    "audio-separator",
]

[tool.pytest.ini_options]
pythonpath = ["."]

